### ISSUE TITLE
sharing client/server-side templates

### ISSUE THREAD

**Issue by freewil** [LearnBoost/jadevu#8]
If I have a jade file used as an "include" or "partial" server-side, how can I also use this to create a template with jadevu?

For example I have `some_section.jade` that I want to use within another jade file server-side but then I also want to generate a client-side template of it. How can I accomplish this? If i try to do something like below the include will be literally taken as part of the template, instead of creating a template of the included file.

_includes/some_section.jade

```
#section= content
```

somepage.jade

```
h2 My Section
include _includes/some_section

template(id='somesection'):
  include _includes/some_section
```

**Comment by tj** [comment]
I'd like to add this to Jade eventually. https://github.com/visionmedia/jade/issues/620

**Comment by freewil** [comment]
Hey thanks TJ - I'm now using `browserijade` which is more heavy-handed and I had to change my approach a bit, but it is kind of nice to be able to expose all my client-side templates in a minified external script.
